    dimensionedScalar Cmu
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "Cmu",
            k1Epsilon1Dict,
            0.22
        )
    );

    dimensionedScalar CmuKEps
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "Cmu",
            k1Epsilon1Dict,
            0.09
        )
    );

    dimensionedScalar C1
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "C1",
            k1Epsilon1Dict,
            1.4
        )
    );

    dimensionedScalar C2
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "C2",
            k1Epsilon1Dict,
            0.3
        )
    );

    dimensionedScalar CL
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "CL",
            k1Epsilon1Dict,
            0.23
        )
    );

    dimensionedScalar Ceta
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "Ceta",
            k1Epsilon1Dict,
            70
        )
    );

    dimensionedScalar Ceps2
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "Ceps2",
            k1Epsilon1Dict,
            1.9
        )
    );

    dimensionedScalar sigmaK
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "sigmaK",
            k1Epsilon1Dict,
            1.0
        )
    );

    dimensionedScalar sigmaEps
    (
        dimensionedScalar::lookupOrAddToDict
        (
            "sigmaEps",
            k1Epsilon1Dict,
            1.3
        )
    );






